### ISSUE TITLE
Error in ELECTRON_ASAR

### ISSUE THREAD

**Issue by annakocheshkova** [Dezeiraud/bsdiff-nodejs#6]
**Describe the bug**
Module fails to start.

**To Reproduce**
```
const bsdiff = require('bsdiff-nodejs');

...

bsdiff.diff(path.resolve("./assets/image.png"), path.resolve("./assets/image2.png"), path.resolve("./assets.patch"), function(result, err) {
            console.log(result + err);
});
```

**Error**
```
Error: A dynamic link library (DLL) initialization routine failed.
\\?\D:\GitHub\...\node_modules\bsdiff-nodejs\build\Release\bsdiff.node
	at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
at Object.Module._extensions..node (module.js:598:18)
	at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:814:682)
	at Function.t.getExtensionPathIndex.then.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:765:373)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (D:\GitHub\...\node_modules\bsdiff-nodejs\index.js:1:171)
	at Object.<anonymous> (D:\GitHub\...\node_modules\bsdiff-nodejs\index.js:3:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:814:682)
	at Function.t.getExtensionPathIndex.then.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:765:373)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (D:\GitHub\...\src\index.js:16:16)
	at Object.<anonymous> (D:\GitHub\...\src\index.js:44:3)	
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:814:682)
	at Function.t.getExtensionPathIndex.then.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:765:373)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
```

**Desktop (please complete the following information):**
 - OS: Windows
- NodeJS version 8.11.1

**Comment by Brouilles** [comment]
Thanks for the report (again!).
You only have the error on Windows or even on Unix system (if you can try) ? 
You have the problem only with Electron ? (electron-builder I suppose because bsdiff-nodejs it's a native Add-on). 

I'm going to do a project under the same conditions as you to see that. We have not yet done a test with Electron on our side. This is the opportunity!

**Comment by annakocheshkova** [comment]
Hi again! I'm actually not using electron anywhere in my project (I have a node js app), so not quite sure why it happens. I'm trying the same on mac.

**Comment by annakocheshkova** [comment]
Confirm the same happens on mac. Seems like ELECTRON_ASAR.js is called from somewhere in your module, as I can see from the stacktrace.

**Comment by Brouilles** [comment]
Hum, ok strange! I will study this in depth, I do not use it explicitly and there was no problem in version 1.0.0.

Thanks again for your help.

**Comment by Brouilles** [comment]
I just configured a very basic nodejs project and I do not have the problem on Mac OS.
Can you put your code in a zip for testing?

I'm on Nodejs v8.11.1 and npm 6.2.0

**Comment by annakocheshkova** [comment]
Hmm, just started with a fresh new app and it worked. Seems to be something in my old project that stops it from working. Thanks and sorry for taking your time ! :)

**Comment by Brouilles** [comment]
Good! We are happy you can use the bsdiff-nodejs, don't hesitate if you have suggestion!
